export const SEARCH_START = 'SEARCH_START';
export const SEARCH_END = 'SEARCH_END';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILLURE = 'SEARCH_FAILLURE';
export const SAVE_INPUT = 'SAVE_INPUT';
